In [1]:
import numpy as np

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [5]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [10]:
arr1 = np.eye(3)

In [11]:
arr1.flatten()

array([1., 0., 0., 0., 1., 0., 0., 0., 1.])

In [12]:
arr1.flatten().tolist()

[1.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0.0, 0.0, 1.0]

- what if we want random integers

In [2]:
import random
random.randint(10,20)

10

In [3]:
import numpy as np
np.random.randint(10)

1

- when we develop ml models we use some data for training and some for testing

- also we will use multiple models for training and testing

- out of these which model gives best result we select that

- so we need every model should test on same data

- this we can achieve by np.random.seed

In [4]:
np.random.seed(42)
np.random.randint(10,50,size = 5)

array([48, 38, 24, 17, 30])

In [5]:
np.random.randint(10,50,size = 5)

array([48, 28, 32, 20, 20])