In [1]:
import numpy as np
l1 = [10,20,30,40]
arr1 = np.array(l1)
arr1

array([10, 20, 30, 40])

In [3]:
arr1.ndim

1

In [4]:
arr1.shape

(4,)

In [5]:
arr1.size

4

In [7]:
l1 = [10,20,30,40]
l2 = [1,2,3,4]
#2d means 2 lists

arr2d = np.array([l1,l2])
arr2d

array([[10, 20, 30, 40],
       [ 1,  2,  3,  4]])

In [8]:
arr2d.ndim

2

In [9]:
arr2d.shape

(2, 4)

In [10]:
arr2d.size

8

In [16]:
l1 = [10,20,30,40]
l2 = [1,2,3,4]
#2d means 2 lists

arr3d = np.array([[l1,l2]])
arr3d

array([[[10, 20, 30, 40],
        [ 1,  2,  3,  4]]])

In [17]:
arr3d.ndim

3

In [18]:
arr3d.size

8

In [19]:
arr3d.shape

(1, 2, 4)

l, m, n: 2,2,4

- n indicates how many elemets we have in a list #4
    - 2,2,4
    - a list has 4 elements : [10,20,30,40]

- m indicates how many lists are available #2
    - m = 2 means 2 lists are available
    - each list how many 4 values
    - one list name is: l1
    - another list name is: l2
    -m : [l1,l2]

-l indicates how many m  #2
    - l = 2 means there are 2 m's available
    - m : [l1,l2]
    - [[l1,l2],[l1,l2]]
    

In [20]:
np.array([[l1,l2],[l1,l2]]).shape

(2, 2, 4)

In [21]:
np.array([l1,l2]).shape

(2, 4)

In [23]:
np.array([[l1,l2],[l1,l2],[l1,l2]]).shape

(3, 2, 4)

In [24]:
np.array([[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]]]).shape

(4, 3, 2, 4)

In [25]:
np.array([[[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]]],[[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]]],[[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]]],[[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]]],[[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]],[[l1,l2],[l1,l2],[l1,l2]]]]).shape

(5, 4, 3, 2, 4)